### PR TITLE
[WIP] Add material for NumPy

### PR DESCRIPTION
**Pull request by redbluee**
This PR contains material for what is numpy, how to use it, doing advanced operations supported with explanations and examples.

### CODE REVIEW

**Comment by s-weigand** [comment]
closes #23

**Comment by s-weigand** [comment]
grafik
😜

**Comment by redbluee** [comment]
I would like to close this PR at this point without merging or so bcs I couldnt finish it then. It makes sense to start-over from here.

issue #23 still open

**Comment by s-weigand** [comment]
Sadly this project never took off as we planned.
At least the [cheat sheet list](https://python-tools-for-students.readthedocs.io/en/latest/material/cheat_sheets.html#cheat-sheets) is till useful

**Pull request closed without merging**
